### PR TITLE
fix can't parse long to string

### PR DESCRIPTION
**Pull request by shmuelko**
parse ids in URI to long for long ids

### CODE REVIEW

**Review by stask — COMMENTED** [review]
I don't understand what this PR fixes.
The ID is parsed from string and converted back to string, what's the point?


Can you add a test that reproduces the issue you trying to fix? That will be the best explanation

**Comment by shmuelko** [comment]
It's a bug in URI parser, if he gets a string that is long he can't parse it, so I help him to parse it

the error is originated from this part of [clj-http](https://github.com/dakrone/clj-http/blob/3.x/src/clj_http/client.clj)
```(defn parse-url
  "Parse a URL string into a map of interesting parts."
  [url]
  (let [url-parsed (URL. url)]
    {:scheme (keyword (.getProtocol url-parsed))
     :server-name (.getHost url-parsed)
     :server-port (when-pos (.getPort url-parsed))
     :url url
     :uri (url-encode-illegal-characters (.getPath url-parsed))
     :user-info (if-let [user-info (.getUserInfo url-parsed)]
                  (util/url-decode user-info))
     :query-string (url-encode-illegal-characters (.getQuery url-parsed))}))```
     
I am not 100% sure why this is happening, but I know that I got this error and after this fix it stoped

**Comment by stask** [comment]
Where exactly it fails? 
Do you have error?

I'm asking because I don't understand how converting string to long and back helps here.

**Comment by shmuelko** [comment]
```Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String

at java.util.concurrent.FutureTask.report(FutureTask.java:122)

at java.util.concurrent.FutureTask.get(FutureTask.java:192)

at clojure.core$deref_future.invokeStatic(core.clj:2304)

at clojure.core$future_call$reify__8477.deref(core.clj:6976)

at clojure.core$deref.invokeStatic(core.clj:2324)

at clojure.core$pmap$step__8490$fn__8494.invoke(core.clj:7027)

at clojure.lang.LazySeq.sval(LazySeq.java:42)

at clojure.lang.LazySeq.seq(LazySeq.java:51)

at clojure.lang.Cons.next(Cons.java:39)

at clojure.lang.RT.next(RT.java:713)

at clojure.core$next__5403.invokeStatic(core.clj:64)

at clojure.core.protocols$fn__8181.invokeStatic(protocols.clj:169)

at clojure.core.protocols$fn__8181.invoke(protocols.clj:124)

at clojure.core.protocols$fn__8136$G__8131__8145.invoke(protocols.clj:19)

at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)

at clojure.core.protocols$fn__8168.invokeStatic(protocols.clj:75)

at clojure.core.protocols$fn__8168.invoke(protocols.clj:75)

at clojure.core.protocols$fn__8110$G__8105__8123.invoke(protocols.clj:13)

at clojure.core$reduce.invokeStatic(core.clj:6830)

at clojure.core$into.invokeStatic(core.clj:6897)

at clojure.core$into.invoke(core.clj:6889)

at practitest_firecracker.practitest$create_or_update_tests.invokeStatic(practitest.clj:539)

at practitest_firecracker.practitest$create_or_update_tests.invoke(practitest.clj:535)

at practitest_firecracker.core$_main.invokeStatic(core.clj:79)

at practitest_firecracker.core$_main.doInvoke(core.clj:31)

at clojure.lang.RestFn.applyTo(RestFn.java:137)

at practitest_firecracker.core.main(Unknown Source)

Caused by: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String

at clj_http.client$parse_url.invokeStatic(client.clj:170)

at clj_http.client$parse_url.invoke(client.clj:170)

at clj_http.client$url_request.invokeStatic(client.clj:1027)

at clj_http.client$url_request.invoke(client.clj:1024)

at clj_http.client$wrap_url$fn__4222.invoke(client.clj:1035)

at clj_http.client$wrap_decompression$fn__3917.invoke(client.clj:416)

at clj_http.client$wrap_input_coercion$fn__4042.invoke(client.clj:630)

at clj_http.client$wrap_additional_header_parsing$fn__4067.invoke(client.clj:685)

at clj_http.client$wrap_output_coercion$fn__4029.invoke(client.clj:574)

at clj_http.client$wrap_exceptions$fn__3870.invoke(client.clj:250)

at clj_http.client$wrap_accept$fn__4082.invoke(client.clj:728)

at clj_http.client$wrap_accept_encoding$fn__4089.invoke(client.clj:750)

at clj_http.client$wrap_content_type$fn__4076.invoke(client.clj:711)

at clj_http.client$wrap_form_params$fn__4187.invoke(client.clj:959)

at clj_http.client$wrap_nested_params$fn__4208.invoke(client.clj:993)

at clj_http.client$wrap_flatten_nested_params$fn__4217.invoke(client.clj:1017)

at clj_http.client$wrap_method$fn__4155.invoke(client.clj:893)

at clj_http.cookies$wrap_cookies$fn__1810.invoke(cookies.clj:128)

at clj_http.links$wrap_links$fn__2943.invoke(links.clj:63)

at clj_http.client$wrap_unknown_host$fn__4225.invoke(client.clj:1046)

at clj_http.client$request_STAR_.invokeStatic(client.clj:1174)

at clj_http.client$request_STAR_.invoke(client.clj:1167)

at clj_http.client$post.invokeStatic(client.clj:1192)

at clj_http.client$post.doInvoke(client.clj:1188)

at clojure.lang.RestFn.applyTo(RestFn.java:139)

at clojure.core$apply.invokeStatic(core.clj:667)

at clojure.core$apply.invoke(core.clj:662)

at throttler.core$fn_throttler$fn__11858$fn__11859.doInvoke(core.clj:171)

at clojure.lang.RestFn.invoke(RestFn.java:421)

at practitest_firecracker.practitest$api_call.invokeStatic(practitest.clj:52)

at practitest_firecracker.practitest$api_call.invoke(practitest.clj:39)

at practitest_firecracker.practitest$ll_find_tests.invokeStatic(practitest.clj:250)

at practitest_firecracker.practitest$ll_find_tests.invoke(practitest.clj:247)

at practitest_firecracker.practitest$create_or_update_tests$fn__12999.invoke(practitest.clj:542)

at clojure.core$pmap$fn__8485$fn__8486.invoke(core.clj:7024)

at clojure.core$binding_conveyor_fn$fn__5772.invoke(core.clj:2034)

at clojure.lang.AFn.call(AFn.java:18)

at java.util.concurrent.FutureTask.run(FutureTask.java:266)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

at java.lang.Thread.run(Thread.java:748)```

**Comment by shmuelko** [comment]
each time we try to build URI in firecracker with very long ids it fails, I think it fix it by helping java to know explicitly it is a long and not something else

**Comment by shmuelko** [comment]
```
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String

at java.util.concurrent.FutureTask.report(FutureTask.java:122)

at java.util.concurrent.FutureTask.get(FutureTask.java:192)

at clojure.core$deref_future.invokeStatic(core.clj:2304)

......

at clojure.lang.RestFn.applyTo(RestFn.java:137)

at practitest_firecracker.core.main(Unknown Source)

Caused by: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String

at clj_http.client$parse_url.invokeStatic(client.clj:170)

......

at throttler.core$fn_throttler$fn__11858$fn__11859.doInvoke(core.clj:171)

at clojure.lang.RestFn.invoke(RestFn.java:421)

at practitest_firecracker.practitest$api_call.invokeStatic(practitest.clj:52)

at practitest_firecracker.practitest$api_call.invoke(practitest.clj:39)

at practitest_firecracker.practitest$ll_find_tests.invokeStatic(practitest.clj:250)

at practitest_firecracker.practitest$ll_find_tests.invoke(practitest.clj:247)

at practitest_firecracker.practitest$create_or_update_tests$fn__12999.invoke(practitest.clj:542)

at clojure.core$pmap$fn__8485$fn__8486.invoke(core.clj:7024)

at clojure.core$binding_conveyor_fn$fn__5772.invoke(core.clj:2034)

at clojure.lang.AFn.call(AFn.java:18)

at java.util.concurrent.FutureTask.run(FutureTask.java:266)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

at java.lang.Thread.run(Thread.java:748)

**Comment by shmuelko** [comment]
maybe I should parse it to string instead

**Comment by shmuelko** [comment]
no, I parse it only if it is a string so that won't help.
I don't know when this string becomes long and then parse-url trying to parse it back to a string, but I know that I got to the point that I am getting this error and if I add this fix this error doesn't jump anymore.

**Comment by yisraeldov** [comment]
There is lots of repeated code here.

Maybe the calls to `parse-id` should be moved to `build-url` ?

**Comment by stask** [comment]
I still don't understand how this exception is fixed by this PR.

The exception says that casting from Long to String cannot be done. 
How does parsing a string to a long and then converting it back to string helps here?

**Comment by shmuelko** [comment]
@yisraeldov, not all the params of bulid-uri will be ids so I can't just cast all the params that build-uri is accepting.
@stask from what I understand the problem is with direct casting that doesn't work, and this is why this explicit parse is working (just a theory)

**Review by yisraeldov — COMMENTED** [review]
In the future, in your commit messages, say the intent of the commit.

No need to say what files are changed, we can see that using `--stats`

**Pull request closed without merging**
